package routes

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "go-gin-project/docs" // docs is generated by Swag CLI
)

// SetupSwaggerRoutes sets up the Swagger UI routes.
func SetupSwaggerRoutes(router *gin.Engine) {
	// Swagger documentation route
	// The URL for swagger UI will be /swagger/index.html
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}

